services:
  nostr-delete:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run dev -- --host 0.0.0.0